spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
#    url: jdbc:h2:file:~/.h2/test;Auto_Server=True;IgnoreCase=True;Mode=MySql
    username: root
    password: abc@123
    name: test
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-test-query: select 'x'
      minimum-idle: 1
      maximum-pool-size: 10
      idle-timeout: 60000
  thymeleaf:
    prefix: classpath:/templates/controller/
    cache: false
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    check-template: true

server:
  port: 8000
  context-path: /
  tomcat:
    uri-encoding: UTF-8
